@host = http://localhost
@port = 5149 
@Restaurants.API_HostAddress = {{host}}:{{port}}
@restaurantID = 1

GET {{Restaurants.API_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/weatherforecast/generate?resultsNumber=6
Content-Type: application/json

{
    "MinimumTemperature": 10,
    "MaximumTemperature": 20
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantID}}
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "Sp",
  "Description": "A culinary experience like no other",
  "Category": "Japanese",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-555"
}