@host = http://localhost
@port = 5149 
@Restaurants.API_HostAddress = {{host}}:{{port}}
@restaurantID = 7

GET {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantID}}
Content-Type: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "Name": "KFC Santa Mónica",
  "Description": "A culinary experience like no other",
  "Category": "American",
  "HasDelivery": true,
  "ContactEmail": "info@kfcdelights.com",
  "ContactNumber": "555-123-4567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-555"
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantID}}

###

PATCH {{Restaurants.API_HostAddress}}/api/restaurants/{{restaurantID}}
Content-Type: application/json

{
  "Name": "KCF California",
  "Description": "Chicken culinary experience in California",
  "HasDevelivery": false
}
